language: ruby
cache: bundler
script: bundle exec rspec
sudo: false

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.2

matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.2.gemfile
